### ISSUE TITLE
Error: "A specified logon session does not exist. It may have already been terminated" 

### ISSUE THREAD

**Issue by JeffB1** [segor/SslCertBinding.Net#10] opened 2017-08-11 07:35 UTC
I am getting the error "A specified logon session does not exist. It may have already been terminated". 

I initially started with my program using your component. I then got frustrated with that and downloaded the source and ran your unit tests. They all fail with same issue. 

I am running on Windows 10 home with Visual Studio running with "Run As Administrator" option. I thought it might have been something I had done wrong in my code but now your unit tests are failing as well :-(

Cheers

Jeff

**Comment by segor** [comment] 2017-08-11 17:31
Hi Jeff, 
I have just run unit-tests on my Win 10 Pro. I can confirm that unit-tests do not work for me also. 
Actually last time I tested this library on Win 8. So I am not sure that it supports Win 10.

Anyway I will be able to look at this issue in a few days.

I also would be happy if you try fixing it.

Thank you,
Sergey

**Comment by JeffB1** [comment] 2017-08-11 20:21
Hi Sergey

At least I know I'm not using the library incorrectly! Hopefully we can work it out. I've had one technical issue after another this week. This is last one hopefully!!

Regards

Jeff Butterworth

On 12 Aug 2017, at 3:31 am, segor <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jeff,
I have just run unit-tests on my Win 10 Pro. I can confirm that unit-tests do not work for me also.
Actually last time I tested this library on Win 8. So I am not sure that it supports Win 10.

Anyway I will be able to look at this issue in a few days.

I also would be happy if you try fixing it.

Thank you,
Sergey

-

**Comment by JeffB1** [comment] 2017-09-04 03:05
Any luck? I've not had much at my end but can't really claim to be much of an expert in this area. I may end up having to look at some sort of scripting to make this work, which would be a shame because this solution is obviously much neater for the end user.

**Comment by segor** [comment] 2017-09-04 13:06
Sorry, I spent a few hours without any success.  I have just googled and figured out a possible solution: https://partnersupport.microsoft.com/en-us/par_servplat/forum/par_winserv/ssl-certificate-error-in-edit-site-bindings/8fabe84e-0500-4d54-980b-db4f7d4c2e94?auth=1

But I am not sure it will help. There are a lot of such issues on Internet :(

**Comment by JeffB1** [comment] 2017-09-12 10:24
Any luck? If I use makecert and netsh http add, I can create certificates and bind them to the required port without getting the error. So I know it's possible. But I just can't get it working via this mechanism or intend anything similar.

**Comment by segor** [comment] 2017-09-12 13:33
@JeffB1 Yes,  I have found a solution. I will commit fix in a few hours. 
The issue is in unit tests, not in the in the library.

**Comment by segor** [comment] 2017-09-12 14:02
@JeffB1 Can you check if my changes in the `dev` branch work for you ?

**Comment by JeffB1** [comment] 2017-09-12 18:12
If it's only unit test issue then why do I get the issue when I use the library in real code?

Regards

Jeff Butterworth

On 12 Sep 2017, at 11:48 pm, segor <notifications@github.com<mailto:notifications@github.com>> wrote:


@JeffB1<https://github.com/jeffb1> Yes, I have found a solution. I will commit fix in a few hours.
The issue is in unit tests, not in the in the library.

-

**Comment by JeffB1** [comment] 2017-09-12 18:43
Unit tests fail. 
AddWithDefaultOptions - line 144
AddWithNonDefaultOptions - line 189
Update - line 290

**Comment by JeffB1** [comment] 2017-09-12 18:49
Debugging the tests it looks like it did actually do the important bit. At the end of the test you are comparing with expected output. However, the actual output includes the following at the start of the text. But it does appear to have bound the ip and cert.

Now if I run the SslCertBinding.Net.Sample and use the bind command param for a cert I had generated by another means, it still fails with the same error. So I think that's indicating the issue is possibly with the cert being generated? Need more investigating.


SSL Certificate bindings: 
-------------------------

**Comment by JeffB1** [comment] 2017-09-12 19:00
@segor so you include a CA cert as a resource in the project then you generate a secondary cert from that one. So how did you generate the CA cert in the first place? Is the 'specified login issue' really coming from cert issues?

**Comment by JeffB1** [comment] 2017-09-12 21:13
@segor  I am finding that if I generate .p12 files and install them, I can bind the cert to the port and it works as required. If I generate just .crt files and install them, they don't work.

**Comment by segor** [comment] 2017-09-12 23:31
@JeffB1 make sure that your certificate is properly installed (valid and has assigned private key) . Links that might help you:
https://support.quovadisglobal.com/kb/a463/how-do-i-know-if-my-certificate-has-the-private-key-attached-within-windows.aspx
https://stackoverflow.com/questions/15671476/how-to-import-an-openssl-key-file-into-the-windows-certificate-store

**Comment by segor** [comment] 2017-10-27 17:06
@JeffB1 Do you still have this problem? May I close the issue?

**Comment by JeffB1** [comment] 2017-10-27 19:14
Can close

Regards

Jeff Butterworth

On 28 Oct 2017, at 3:06 am, segor <notifications@github.com<mailto:notifications@github.com>> wrote:


@JeffB1<https://github.com/jeffb1> Do you still have this problem? May I close the issue?

-

**Closed** 2017-10-27 20:56 UTC
Labels: bug

**Comment by suityou01** [comment] 2018-03-10 09:54
I have generated a certificate using the crypto32 api in c#. I have registered the certificate in the cert store (local machine) and when I view in certmgr I can see that a private key is set. However I still get the error.

From reading the thread, it does rather look like there are some baseline requirements for generating a cert that need to be documented, ie in real terms what are the key differences (pun intended) for a certificate generated by makecert, and my effort using the crypto api.

For info, the code used to generate the certificate is eerily similar to the code used in this article ;)

https://www.dima.to/blog/?p=290

Any help or guidance greatly appreciated.

**Comment by sergeyg-earnin** [comment] 2018-03-10 12:25
Hi @suityou01 ,
You can see requirements for generating a cer in documentation for command `netsh add sslcert`. 
Have you tried to bind your certificate  using the command `netsh add sslcert` ? If you get the same error then it is an issue with your certificate or system configuration.  

If `netsh` works for you look at  unit tests from `dev` branch how to install a certificate. Try running unit tests on your PC. Replace the predefined certificate with yours and see if the library can work with your certificate.

**Comment by suityou01** [comment] 2018-03-10 13:19
Thank you sergeyg. I will try all of these things you suggest. I was indeed running VS as the admin user. :)
I will let you know how I get on.

**Comment by suityou01** [comment] 2018-03-12 20:08
OK my findings are as follows 

Running the unit tests works.
Replacing the certificate with your certificate in my code produces the same error.
Lifting the code from your unit tests into my code does not work.

This is my code, which is running as admin, using your certificate, that produces this error : 

public static void BindCertificateToSSLPort(X509Certificate2 certContext)
        {
            var config = new CertificateBindingConfiguration();
            var certificateThumbprint = certContext.Thumbprint;
            //var appId = Guid.Parse("dbb7fab4-d706-45cc-b67d-19f1a281ba34");
            //var appId = Guid.Parse("8f93baff-b90b-4a3f-8266-9f4f19401df9"); //classlib
            var appId = Guid.NewGuid();

            // add a new binding record
            config.Bind(new CertificateBinding(
                certificateThumbprint, StoreName.My, ipPort, appId, new BindingOptions
                {
                    DoNotPassRequestsToRawFilters = true,
                    DoNotVerifyCertificateRevocation = true,
                    EnableRevocationFreshnessTime = true,
                    NegotiateCertificate = true,
                    NoUsageCheck = true,
                    RevocationFreshnessTime = TimeSpan.FromMinutes(1),
                    RevocationUrlRetrievalTimeout = TimeSpan.FromSeconds(5),
                    UseDsMappers = true,
                    VerifyRevocationWithCachedCertificateOnly = true,
                })); //returns false


            config.Delete(ipPort);
        }

I am stumped, as the values passed into the bind method are identical to when I run it through as the unit test.

What on earth can I be doing wrong?

**Comment by suityou01** [comment] 2018-03-12 20:16
Wait, I lied. Your unit tests give the same error as well. Phew! At least it's consistent.

Any thoughts as to why this would fail straight out of github?

**Comment by suityou01** [comment] 2018-03-12 20:18
In fact, all unit tests fail with the same error. Running VS2017 community edition as Admin.

**Comment by suityou01** [comment] 2018-03-12 21:00
And running netsh http add sslcert ipport=0.0.0.0:50000 certhash=68BC1AACBC38F564B95E1499FA2BA0FC30899A3E appid={48358cac-7fe0-4f78-95ba-326dcd436df6} certstorename=My 

from an elevated command prompt gives this error

SSL Certificate add failed, Error: 1312
A specified logon session does not exist. It may already have been terminated.

**Comment by suityou01** [comment] 2018-03-13 19:18
Will you re-open the issue? Any thoughts?

**Comment by segor** [comment] 2018-03-14 09:47
@suityou01, if netsh fails with any certificates I think you need to reconfigure your PC. Please  make sure that netsh is working with your certificate first. If it does work then this library should also work because they use the same `Http Api` inside.

**Comment by segor** [comment] 2018-03-14 11:52
FAQ added in https://github.com/segor/SslCertBinding.Net/commit/b6a5921cee3628ed5f887fa0203b652fd86afb3e
